version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spacetime-postgres
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacetime_db
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: always
    networks:
      - spacetime-network

networks:
  spacetime-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
